/*
 * This source file was generated by the Gradle 'init' task
 */
package hw9;

public class App {

    public static void main(String[] args) {
        try {
            new HttpImageStatusCli().askStatus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
